version: "3.3"

services:
    expo_server:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/app
        env_file: .env
        ports:
            - 19000:19000
            - 19001:19001
            - 19002:19002
    
